# Generated by Django 6.0.4 on 2026-05-04 19:46

from django.db import migrations

SECTIONS = [
    {'order': 1,  'name': 'Introduction',
     'url_name': 'webapp:introduction', 'slug': 'introduction',
     'desc': 'Overview of the co-development process, toolkit structure, and guiding principles.'},
    {'order': 2,  'name': 'Designing for Impact',
     'url_name': 'webapp:designing_for_impact', 'slug': 'designing-for-impact',
     'desc': 'Build a results framework linking EO capabilities to real-world outcomes and impacts.'},
    {'order': 3,  'name': 'Capturing & Communicating Impact',
     'url_name': 'webapp:capturing_communicating_impact', 'slug': 'capturing-communicating-impact',
     'desc': 'Document and share evidence of solution effectiveness through use cases and case studies.'},
    {'order': 4,  'name': 'Economic Impact Assessments',
     'url_name': 'webapp:economic_impact_assessments', 'slug': 'economic-impact-assessments',
     'desc': 'Quantify the economic value of EO-enabled decision improvements.'},
    {'order': 5,  'name': 'Stakeholder Mapping & Analysis',
     'url_name': 'webapp:stakeholder_mapping', 'slug': 'stakeholder-mapping',
     'desc': 'Identify, prioritize, and engage the people who shape solution success.'},
    {'order': 6,  'name': 'Needs Assessment',
     'url_name': 'webapp:needs_assessment', 'slug': 'needs-assessment',
     'desc': 'Understand decision-maker needs, constraints, and information gaps.'},
    {'order': 7,  'name': 'Information Chain Analysis',
     'url_name': 'webapp:information_chain_analysis', 'slug': 'information-chain-analysis',
     'desc': 'Trace how information flows from data source to decision-maker.'},
    {'order': 8,  'name': 'User-Centered Design',
     'url_name': 'webapp:user_centered_design', 'slug': 'user-centered-design',
     'desc': 'Design solutions around real-world decision contexts and user constraints.'},
    {'order': 9,  'name': 'Technical Requirements Template',
     'url_name': 'webapp:technical_requirements', 'slug': 'technical-requirements',
     'desc': 'Specify system, data, and interface requirements for solution development.'},
    {'order': 10, 'name': 'Data Governance & Storage',
     'url_name': 'webapp:data_governance', 'slug': 'data-governance',
     'desc': 'Plan for FAIR data management, sharing, and long-term preservation.'},
    {'order': 11, 'name': 'Implementation & Monitoring Plan',
     'url_name': 'webapp:implementation_monitoring', 'slug': 'implementation-monitoring',
     'desc': 'Track milestones, resources, and impact across the solution lifecycle.'},
    {'order': 12, 'name': 'Adoption & Sustainability Plan',
     'url_name': 'webapp:adoption_sustainability', 'slug': 'adoption-sustainability',
     'desc': 'Ensure solutions are adopted, maintained, and sustained beyond development.'},
    {'order': 13, 'name': 'Meaningful Metrics Development',
     'url_name': 'webapp:meaningful_metrics', 'slug': 'meaningful-metrics',
     'desc': 'Design metrics that validate progress and demonstrate solution impact.'},
]


def seed_forward(apps, schema_editor):
    NavSection = apps.get_model('webapp', 'NavSection')
    NavSection.objects.bulk_create([NavSection(**s) for s in SECTIONS])


def seed_reverse(apps, schema_editor):
    NavSection = apps.get_model('webapp', 'NavSection')
    NavSection.objects.filter(slug__in=[s['slug'] for s in SECTIONS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_forward, seed_reverse),
    ]
