# Generated by Django 6.0.4 on 2026-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_seed_navsections"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=500)),
                ("filename", models.CharField(max_length=500)),
                ("file_path", models.CharField(max_length=1000, unique=True)),
                ("chunk_count", models.IntegerField(default=0)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
    ]
