# Generated by Django 6.0.4 on 2026-05-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0004_pagecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="navsection",
            name="is_dynamic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="navsection",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="navsection",
            name="url_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
