# Generated by Django 6.0.4 on 2026-06-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0005_navsection_dynamic_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
                ("prompt", models.TextField()),
                ("response", models.TextField(blank=True)),
                ("page_url", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-asked_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("general", "General feedback"),
                            ("chat_issue", "Chat issue"),
                            ("bug_report", "Bug report"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("feedback_text", models.TextField()),
                ("page_url", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
