# Generated by Django 6.0.4 on 2026-06-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0006_visitor_feedback_chat_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorfeedback",
            name="chat_prompt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="response_feedback",
                to="webapp.chatprompt",
            ),
        ),
        migrations.AddField(
            model_name="visitorfeedback",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[("up", "Thumbs up"), ("down", "Thumbs down")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visitorfeedback",
            name="feedback_text",
            field=models.TextField(blank=True),
        ),
    ]
